### ISSUE TITLE
Window title match does not work

### ISSUE THREAD

**Issue by vilbur** [RaptorX/AHK-ToolKit#3]
Hello,
I`m not able to set  window title match in advance options. I tried whole title, part of title, RegEx... nothing works. It is quite possible, that I have some mistake in syntax, (  AHK script is not suitable for me ). Can you provide some example of "If window active list" please ?

**Comment by RaptorX** [comment]
Hi, that is one option that i havent coded.

I had to stop coding AHK-Toolkit a while ago because of changing to another
country. I do plan on resuming coding but I cant actually tell you when
will that be available again.

On Tue, May 3, 2016 at 10:46 PM, vilbur <notifications@github.com> wrote:

> Hello,
> I`m not able to set window title match in advance options. I tried whole
> title, part of title, RegEx... nothing works. It is quite possible, that I
> have some mistake in syntax, ( AHK script is not suitable for me ). Can you
> provide some example of "If window active list" please ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/RaptorX/AHK-ToolKit/issues/3>
>



-- 

*ΓΝΩΘΙ﻿ Σ'ΑΥΤΟΝvindicta bonum vita iucundius ipsa*
++++++++++++++++++++++++++++++

**Comment by vilbur** [comment]
Hello RaptorX,
Please fix this isssue, please, please, please ;)
